name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      tag:
        description: "v0.0.0"
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          path: build

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: >
          npx web-ext sign
            --source-dir src
            --artifacts-dir build
            --channel listed
            --id $WEB_EXT_ID
            --api-key $WEB_EXT_API_KEY
            --api-secret $WEB_EXT_API_SECRET
        env:
          WEB_EXT_ID: ${{ vars.AMO_UUID }}
          WEB_EXT_API_KEY: ${{ secrets.AMO_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.AMO_API_SECRET }}
      - uses: actions/upload-artifact@v4
        with:
          path: build

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    env:
      version: ${{ github.event.inputs.tag || github.ref }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact # otherwise, it will download all artifacts, creating a subdirectory for each artifact.
          path: build
      - id: major_version
        run: >
          echo major_version=$(
            echo "$version" | cut -d'v' -f2 | cut -d'.' -f1
          ) >> $GITHUB_OUTPUT
      - id: is_release_candidate
        run: >
          echo is_release_candidate=$(
            echo "$version" | grep -c 'rc'
          ) >> $GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ steps.major_version.outputs.major_version == 0 || steps.is_release_candidate.outputs.is_release_candidate == 1 }}
          generate_release_notes: true
          files: build/*
